name: CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: setup poetry
        uses: snok/install-poetry@v1.3.1
      - run: poetry update
      - run: poetry run nox --force-pythons ${{ matrix.python-version }}
      - run: poetry run pytest --cov openapydantic/ tests/
